server:
  port: 8081

spring:
  flyway:
    enabled: true
    baselineOnMigrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: validate